package com.Innova.bank.enums;

public enum AuditAction {
    REGISTER_CUSTOMER,
    REGISTER_STAFF,
    LOGIN,
    LOGOUT,
    REFRESH_TOKEN,
    FAILED_LOGIN,
    CHANGE_PASSWORD,
    DELETE_USER,
    ACCESS_PROTECTED_RESOURCE,
    UPDATE_PROFILE,
    UPDATE_ROLE,
    USER_UNBLOCKED,
    CREATE_ACCOUNT, UPDATE_ACCOUNT_STATUS, CREATE_TRANSFER, CREATE_DEPOSIT, CREATE_WITHDRAWAL, UPDATE_USER_STATUS
}
