package com.Innova.bank.enums;

public enum AuditAction {
    REGISTER,
    LOGIN,
    LOGOUT,
    REFRESH_TOKEN,
    FAILED_LOGIN,
    CHANGE_PASSWORD,
    DELETE_USER,
    ACCESS_PROTECTED_RESOURCE,
    UPDATE_PROFILE,
    UPDATE_ROLE,
    CREATE_ACCOUNT, UPDATE_ACCOUNT_STATUS, UPDATE_USER_STATUS
}
