package com.Innova.bank.enums;

public enum ErrorCode {
    INVALID_CREDENTIALS,
    REFRESH_TOKEN_EXPIRED,
    REFRESH_TOKEN_INVALID,
    USER_NOT_FOUND,
    USER_NOT_ACTIVE,
    UNAUTHORIZED,
    FORBIDDEN,
    RESOURCE_NOT_FOUND,
    VALIDATION_ERROR,
    BAD_REQUEST,
    INTERNAL_SERVER_ERROR
}
